### ISSUE TITLE
Duration column in search shows negative number if only timestamp present

### ISSUE THREAD

**Issue by bpartridge** [hyperdxio/hyperdx#15]
From the demo, if you turn on the Duration column, and an event has a `timestamp` but not `duration` (and presumably not an end time, either), it seems to be subtracting the timestamp from 0 and inventing a negative duration.

(Separately, Duration might be a useful column to show by default in the demo - showing that this isn't just a log aggregator, but something designed to understand entire request-response cycles!)

https://www.hyperdx.io/search?from=1695145472000&to=1695146372000&tq=Sep+19+13%3A44%3A32+-+Sep+19+13%3A59%3A32&lid=e6a41903-0505-407e-848b-26a21081b833&sk=1695146367784000000

<img width="1764" alt="Screenshot 2023-09-19 at 2 03 44 PM" src="https://github.com/hyperdxio/hyperdx/assets/20748/97808ef0-a18c-4161-a1bd-4993af123242">

**Comment by wrn14897** [comment]
Hey bpartridge,

Thanks for reporting the bug here. This particular line is actually a 'log' not 'span', which means it doesn't have duration. Normally, the span has level 'ok' or 'error'. UI wise, I agree we need to show the type to make it clear.
Since log doesn't have duration, the UI should not display anything in that regard. I'm going to file this ticket and this should be a quick fix. Thanks for the contribution.

**Comment by mark-omarov** [comment]
Hey @wrn14897,

I've noticed records with no `type` having the same issue:
<details>
<summary>Screenshot</summary>
<img width="1171" alt="Screenshot 2023-09-22 at 18 08 37" src="https://github.com/hyperdxio/hyperdx/assets/15357910/c478af06-eba5-4b9d-9084-761fb312eb0c">
</details>

Is it safe to assume every event with negative duration doesn't support it and should not be visible?

My first idea was to modify the API response to return `null` or omit the `duration` field, instead of a negative number. I'm not so sure anymore, this will require update on the UI anyways, and I don't think having a field that can be of type `number` and `string` is great.

I am thinking to have a check at the UI table. If the value is negative - display "N/A" or similar, otherwise - display the amount. Only for the `duration` field.

Do you think we could do that? Is it okay if I work on it?

**Comment by wrn14897** [comment]
> Hey @wrn14897,
> 
> I've noticed records with no `type` having the same issue:
> 
> Screenshot
> Is it safe to assume every event with negative duration doesn't support it and should not be visible?
> 
> My first idea was to modify the API response to return `null` or omit the `duration` field, instead of a negative number. I'm not so sure anymore, this will require update on the UI anyways, and I don't think having a field that can be of type `number` and `string` is great.
> 
> I am thinking to have a check at the UI table. If the value is negative - display "N/A" or similar, otherwise - display the amount. Only for the `duration` field.
> 
> Do you think we could do that? Is it okay if I work on it?

This negative number issue is a bit tricky since the 'duration' is a materialized column computed by 'timestamp' and 'end_timestamp' columns. For non log type of lines, the endTime is unix 0 and  that's why you see a negative number. I think the right way is to make ingestor send the 'duration' instead of endTime. The quick fix for now is to set the endTime to be startTime if not specified so the duration is 0 (which makes sense for log). I think I can take this ticket and pull up the fix shortly. Really appreciate for the contribution.
